// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8GrhAlZehWF4DmP2HnpZwhzSYtK46lA',
    appId: '1:961411800758:web:19350fab9d70d940449017',
    messagingSenderId: '961411800758',
    projectId: 'prototype-saham',
    authDomain: 'prototype-saham.firebaseapp.com',
    storageBucket: 'prototype-saham.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLwQdBvV9XrN-CAK_JW57qCcZpjJ9iN8',
    appId: '1:961411800758:android:d64176801a6abb37449017',
    messagingSenderId: '961411800758',
    projectId: 'prototype-saham',
    storageBucket: 'prototype-saham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuEVmRUkZAJNR_NWpAVSn1K1iV2EfKfKQ',
    appId: '1:961411800758:ios:ed11b782d8289f8f449017',
    messagingSenderId: '961411800758',
    projectId: 'prototype-saham',
    storageBucket: 'prototype-saham.appspot.com',
    iosClientId: '961411800758-ej748bomph4m9t4o5l2lgcia919j5phd.apps.googleusercontent.com',
    iosBundleId: 'com.example.saham01App',
  );
}
